SENDER_EMAIL_ID = "ashwinraj.test@gmail.com"
SENDER_EMAIL_PASSWORD = "shrveuemhlklwcsa"

TMDB_API_KEY = 'https://api.themoviedb.org/3/movie/{}?api_key=8d2beee4b9a58936c45ec0e107239142&language=en-US'
YOUTUBE_API_KEY = 'AIzaSyDqs_XIHKyAyrZKrMjUNmtNvK_P_BrnqHw'
OMDB_API_KEY = '8f796424'

AZURE_CONTAINER_NAME = "verticalx-webapp"
AZURE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=verticalxblobstorage;AccountKey=xGZU8Rimp5HvDb3GMcUu+XG00Zi6q9rMUQ/XMwrULAWD1CYWR9Uy8GyCaA93r/fmJnreU64Ak9nq+AStH8q7wQ==;EndpointSuffix=core.windows.net"